#Installs HTTPS Apache on CentOS 7

- name: Set hostname - CentOS
  hostname:
    name: '{{ hostname }}'

- name: Install Apache and dependencies - CentOS
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - httpd
    - setroubleshoot-server
    - unzip
    - libselinux-python
    - mod_ssl

- name: Create certificate directory - CentOS
  file:
    path: /etc/httpd/ssl/
    state: directory
    
- name: Generate self-signed HTTPS certificates - CentOS
  command: openssl req -new -nodes -x509 -subj "/C={{ country }}/ST={{ state }}/L={{ city }}/O={{ org }}/CN={{ hostname }}" -days 3650 -keyout /etc/httpd/ssl/apache.key -out /etc/httpd/ssl/apache.crt -extensions v3_ca creates=/etc/httpd/ssl/apache.crt

- name: Create Apache configuration file - CentOS
  blockinfile:
    path: /etc/httpd/conf.d/apache.conf
    create: yes
    block: |
      <VirtualHost *:443>
        ServerName {{ hostname }}
        ServerAlias {{ ansible_default_ipv4.address }}
        SSLEngine on
        SSLCertificateFile      /etc/httpd/ssl/apache.crt
        SSLCertificateKeyFile /etc/httpd/ssl/apache.key
        # HSTS (mod_headers is required) (15768000 seconds = 6 months)
        <IfModule mod_headers.c>
          Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
        </IfModule>
        # Prevent HTTP XSS Trace attack
        RewriteEngine on
        RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
        RewriteRule .* - [F]
      </VirtualHost>
      # SSL Configuration - generated by Mozilla
      SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
      SSLCipherSuite          ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      SSLHonorCipherOrder     on
      SSLCompression          off
      # OCSP Stapling, only in httpd 2.3.3 and later
      SSLUseStapling          on
      SSLStaplingResponderTimeout 5
      SSLStaplingReturnResponderErrors off
      SSLStaplingCache        shmcb:/var/run/ocsp(128000)
      <Directory /var/www/html/>
        Options +FollowSymlinks
        AllowOverride All
        <IfModule mod_dav.c>
          Dav off
        </IfModule>
        SetEnv HOME /var/www/html
        SetEnv HTTP_HOME /var/www/html
      </Directory>
      Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure

- name: Restart Apache and set it to start at boot - CentOS
  systemd: 
    name: httpd
    state: restarted
    enabled: yes

- name: Open firewall - CentOS
  firewalld:
    port: 443/tcp
    state: enabled
    permanent: yes
    immediate: yes