#Installs HTTPS Apache on Ubuntu 16.04
  
- name: Set hostname
  hostname:
    name: '{{ hostname }}'

- name: Install Apache and dependencies
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - apache2
    
- name: Create cert directory
  file:
    path: /etc/apache2/ssl/
    state: directory
    
- name: Generate HTTPS Certs
  command: openssl req -new -nodes -x509 -subj "/C={{ country }}/ST={{ state }}/L={{ city }}/O={{ org }}/CN={{ hostname }}" -days 3650 -keyout /etc/apache2/ssl/lamp.key -out /etc/apache2/ssl/lamp.crt -extensions v3_ca creates=/etc/apache2/ssl/lamp.crt

- name: Enable Apache SSL Module
  apache2_module:
    name: '{{ item }}'
    state: present
  with_items: 
  - ssl
  - rewrite
  - headers
  
- name: Create Apache config file
  blockinfile:
    path: /etc/apache2/sites-available/lamp.conf
    create: yes
    block: |
      <VirtualHost *:443>
        ServerName {{ hostname }}
        ServerAlias {{ ansible_default_ipv4.address }}
        SSLEngine on
        SSLCertificateFile      /etc/apache2/ssl/lamp.crt
        SSLCertificateKeyFile /etc/apache2/ssl/lamp.key
        # HSTS (mod_headers is required) (15768000 seconds = 6 months)
        <IfModule mod_headers.c>
          Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
        </IfModule>
        # Prevent HTTP XSS Trace attack
        RewriteEngine on
        RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
        RewriteRule .* - [F]
      </VirtualHost>
      # SSL Configuration - generated by Mozilla
      SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
      SSLCipherSuite          ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      SSLHonorCipherOrder     on
      SSLCompression          off
      # OCSP Stapling, only in httpd 2.3.3 and later
      SSLUseStapling          on
      SSLStaplingResponderTimeout 5
      SSLStaplingReturnResponderErrors off
      SSLStaplingCache        shmcb:/var/run/ocsp(128000)
      <Directory /var/www/html/>
        Options +FollowSymlinks
        AllowOverride All
        <IfModule mod_dav.c>
          Dav off
        </IfModule>
        SetEnv HOME /var/www/html
        SetEnv HTTP_HOME /var/www/html
      </Directory>
      Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure

- name: Activate Apache config file
  file:
    src: /etc/apache2/sites-available/lamp.conf
    dest: /etc/apache2/sites-enabled/lamp.conf
    state: link

- name: Restart Apache to apply config changes and set to start at boot
  systemd:
    name: apache2
    state: restarted
    enabled: yes

- name: Open firewall
  ufw:
    state: enabled
    port: '{{ item }}'
    proto: tcp
    rule: allow
  with_items:
  - 22
  - 443