---
- name: Reboot
  hosts: all
  become: true
  tasks:
    - name: Reboot host
      shell: sleep 2 && shutdown -r now "Triggered by Ansible"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for host to come back online
      local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=60