---
- name: Update host
  hosts: all
  become: true

# Skip gathering facts at the beginning, to prevent errors if Python is not installed
  gather_facts: false

# Make sure Python is installed on our Ubuntu hosts, before we try to run anything
  pre_tasks:
  - name: Check if this is Ubuntu
    raw: bash -c "test -e /etc/lsb-release"
    register: ubuntu
    ignore_errors: yes

  - name: Install Python 2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
    when: ubuntu

# Gather the facts after we confirm Python is installed
  - name: Gathering Facts
    setup:

  tasks:
    - name: Update repositories and installed packages - CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == "CentOS"
      
    - name: Auto-remove orphaned dependencies - CentOS
      yum:
        autoremove: true
      when: ansible_distribution == "CentOS"

    - name: Update repositories - Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"  
      
    - name: Update installed packages - Ubuntu
      apt:
        upgrade: full
      when: ansible_distribution == "Ubuntu"  
      
    - name: Auto-remove orphaned dependencies and repo listings- Ubuntu
      apt:
        autoremove: yes
        autoclean: yes
      when: ansible_distribution == "Ubuntu"  