#Installs Wordpress on Ubuntu 16.04

- name: Install Wordpress dependencies - Ubuntu
  apt:
    name: php-gd,unzip
    state: latest

- name: Create a database for WordPress - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  changed_when: False
  with_items:
  - CREATE DATABASE wordpress
  ignore_errors: True

- name: Create WordPress database user - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  changed_when: False
  with_items:
  - CREATE USER 'wordpress' IDENTIFIED BY '{{ mysql_wordpress_password }}'
  ignore_errors: True

- name: Grant privileges to WordPress database user - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  changed_when: False
  with_items:
  - GRANT ALL privileges ON `wordpress`.* TO 'wordpress'@localhost IDENTIFIED BY '{{ mysql_wordpress_password }}'

- name: Reload privilege tables - Ubuntu
  command: 'mysql -u root -ne "FLUSH PRIVILEGES"'
  changed_when: False
    
- name: Check if WordPress is already in the webroot - Ubuntu
  stat:
    path: /var/www/html/wp-config.php
  register: wordpress_files

- name: Download and unzip WordPress - Ubuntu
  when: wordpress_files.stat.exists == False
  unarchive:
    src: http://wordpress.org/latest.zip
    dest: /var/www/
    remote_src: yes
        
- name: Move WordPress directory to webroot - Ubuntu
  when: wordpress_files.stat.exists == False
  command: '{{ item }}'
  with_items:
  - rm -r /var/www/html/
  - mv /var/www/wordpress /var/www/html
  
- name: Create uploads directory - Ubuntu
  file:
    path: /var/www/html/wp-content/uploads
    state: directory
    
- name: Upload wp-config.php - Ubuntu
  when: wordpress_files.stat.exists == False
  template: 
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: www-data
    group: www-data
    mode: 0644

- name: Restart Apache to apply configuration changes - Ubuntu
  systemd:
    name: apache2
    state: restarted