#Installs Nextcloud 12 on Ubuntu 16.04

- name: Install Nextcloud dependencies
  apt:
    name: unzip
    state: latest

- name: Create a database named "nextcloud"
  mysql_db:
    name: nextcloud
    state: present

- name: Create nextcloud database user
  mysql_user:
    name: nextcloud
    password: '{{ mysql_nextcloud_password }}'
    priv: 'nextcloud.*:ALL'
    state: present

- name: Reload privilege tables
  command: 'mysql -ne "FLUSH PRIVILEGES"'
  changed_when: False

- name: Check if Nextcloud is already in the WebRoot
  stat:
    path: /var/www/html/index.php
  register: nextcloud_files

- name: Download and unzip Nextcloud
  when: nextcloud_files.stat.exists == False
  unarchive:
    src: https://download.nextcloud.com/server/releases/latest-12.zip
    dest: /var/www/
    remote_src: yes
        
- name: Move Nextcloud directory to WebRoot
  when: nextcloud_files.stat.exists == False
  command: '{{ item }}'
  with_items:
  - rm -r /var/www/html/
  - mv /var/www/nextcloud /var/www/html
  
- name: Create data directory
  file:
    path: /var/www/html/data
    state: directory
    
- name: Set ownership on WebRoot
  file: 
    path: /var/www/html/
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- name: Backup opcache.ini
  command: mv /etc/php/7.0/apache2/conf.d/10-opcache.ini /etc/php/7.0/apache2/conf.d/10-opcache.ini.bak
  
- name: Apply recommended opcache config
  blockinfile:
    path: /etc/php/7.0/apache2/conf.d/10-opcache.ini
    create: yes
    block: |
      zend_extension=opcache.so
      opcache.enable=1
      opcache.enable_cli=1
      opcache.interned_strings_buffer=8
      opcache.max_accelerated_files=10000
      opcache.memory_consumption=128
      opcache.save_comments=1
      opcache.revalidate_freq=1 

- name: Restart Apache to apply config changes
  systemd:
    name: apache2
    state: restarted