#Installs Nextcloud 15 on Ubuntu 18.04

- name: Install Nextcloud dependencies - Ubuntu
  apt:
    name: unzip
    state: latest

- name: Create a database for Nextcloud - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  changed_when: False
  with_items:
  - CREATE DATABASE nextcloud
  ignore_errors: True

- name: Create Nextcloud database user - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  changed_when: False
  with_items:
  - CREATE USER 'nextcloud' IDENTIFIED BY '{{ mysql_nextcloud_password }}'
  ignore_errors: True

- name: Grant privileges to Nextcloud database user - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  changed_when: False
  with_items:
  - GRANT ALL privileges ON `nextcloud`.* TO 'nextcloud'@localhost IDENTIFIED BY '{{ mysql_nextcloud_password }}'

- name: Reload privilege tables - Ubuntu
  command: 'mysql -u root -ne "FLUSH PRIVILEGES"'
  changed_when: False

- name: Check if Nextcloud is already in the webroot - Ubuntu
  stat:
    path: /var/www/html/index.php
  register: nextcloud_files

- name: Download and unzip Nextcloud - Ubuntu
  when: nextcloud_files.stat.exists == False
  unarchive:
    src: https://download.nextcloud.com/server/releases/latest-15.zip
    dest: /var/www/
    remote_src: yes
        
- name: Move Nextcloud directory to webroot - Ubuntu
  when: nextcloud_files.stat.exists == False
  command: '{{ item }}'
  with_items:
  - rm -r /var/www/html/
  - mv /var/www/nextcloud /var/www/html
  
- name: Create data directory - Ubuntu
  file:
    path: /var/www/html/data
    state: directory
    
- name: Set ownership on webroot - Ubuntu
  file: 
    path: /var/www/html/
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- name: Backup opcache.ini - Ubuntu
  command: mv /etc/php/7.2/apache2/conf.d/10-opcache.ini /etc/php/7.2/apache2/conf.d/10-opcache.ini.bak
  
- name: Apply recommended opcache configuration - Ubuntu
  blockinfile:
    path: /etc/php/7.2/apache2/conf.d/10-opcache.ini
    create: yes
    block: |
      zend_extension=opcache.so
      opcache.enable=1
      opcache.enable_cli=1
      opcache.interned_strings_buffer=8
      opcache.max_accelerated_files=10000
      opcache.memory_consumption=128
      opcache.save_comments=1
      opcache.revalidate_freq=1 

- name: Restart Apache to apply configuration changes - Ubuntu
  systemd:
    name: apache2
    state: restarted