#Installs Nextcloud 12 on CentOS 7

---
- name: Install Nextcloud instance
  hosts: all
  tasks:
    - name: Import variables
      include_vars:
        file: nextcloud_vars.yml
    
    - name: Set hostname
      hostname:
        name: '{{ hostname }}'
        
    - name: Install EPEL package repo.
      yum:
        name: epel-release
        state: latest
  
    - name: Install Webtatic package repo.
      yum:
        name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
        state: present
  
    - name: Update installed packages
      yum:
        name: '*'
        state: latest
  
    - name: Install Nextcloud dependencies
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
        - httpd
        - php70w
        - php70w-dom
        - php70w-mbstring
        - php70w-gd
        - php70w-pdo
        - php70w-json
        - php70w-xml
        - php70w-zip
        - php70w-curl
        - php70w-mcrypt
        - php70w-pear
        - php70w-opcache
        - php70w-pecl-apcu
        - setroubleshoot-server
        - php70w-mysql
        - unzip
        - libselinux-python
        - policycoreutils-python
        - libsemanage-python
        - mariadb-server
        - mariadb-devel
        - python-pip
        - gcc
        - python-devel
        - mod_ssl
        
    - name: Install MySQLDb Python Module
      pip:
        name: MySQL-Python
        state: latest
        
    - name: Set Apache and MariaDB to start at boot
      systemd: 
        name: '{{ item }}'
        state: started
        enabled: yes
      with_items:
      - httpd
      - mariadb
      
#mysql_secure_installlation
    - name: Set root password
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present check_implicit_admin=yes login_password={{ mysql_root_password }}
      with_items:
        - localhost
        - 127.0.0.1
        - ::1

    - name: Add .my.cnf
      template: src='{{ mysql_root_mycnf }}' dest=/root/.my.cnf owner=root group=root mode=0600
      
    - name: Reload privilege tables
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False

    - name: Remove anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    - name: Disallow root login remotely
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      changed_when: False

    - name: Remove test database and access to it
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DROP DATABASE test
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
      changed_when: False
      ignore_errors: True

    - name: Reload privilege tables
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False

    - name: Create a database named "nextcloud"
      mysql_db:
        name: nextcloud
        state: present

    - name: Create nextcloud database user
      mysql_user:
        name: nextcloud
        password: '{{ mysql_nextcloud_password }}'
        priv: 'nextcloud.*:ALL'
        state: present
    
    - name: Reload privilege tables
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False
    
    - name: Restart httpd to load MySQL PHP extension
      systemd:
        name: httpd
        state: restarted
        
    - name: Download and unzip Nextcloud
      unarchive:
        src: https://download.nextcloud.com/server/releases/latest-12.zip
        dest: /var/www/
        remote_src: yes
        
    - name: Move Nextcloud directory to WebRoot
      command: '{{ item }}'
      with_items:
      - rm -r /var/www/html/
      - mv /var/www/nextcloud /var/www/html
      
    - name: Create data directory
      file:
        path: /var/www/html/data
        state: directory
        
    - name: Set permissions on WebRoot
      file: 
        path: /var/www/html/
        owner: apache
        group: apache
        recurse: yes
        state: directory
  
    - name: Create cert directory
      file:
        path: /etc/httpd/ssl/
        state: directory
        
    - name: Generate HTTPS Certs
      command: openssl req -new -nodes -x509 -subj "/C={{ country }}/ST={{ state }}/L={{ city }}/O={{ org }}/CN={{ hostname }}" -days 3650 -keyout /etc/httpd/ssl/nextcloud.key -out /etc/httpd/ssl/nextcloud.crt -extensions v3_ca creates=/etc/httpd/ssl/nextcloud.crt
   
    - name: Create Apache config file
      blockinfile:
        path: /etc/httpd/conf.d/nextcloud.conf
        create: yes
        block: |
          <VirtualHost *:443>
            ServerName {{ hostname }}
            ServerAlias {{ ansible_default_ipv4.address }}
            SSLEngine on
            SSLCertificateFile      /etc/httpd/ssl/nextcloud.crt
            SSLCertificateKeyFile /etc/httpd/ssl/nextcloud.key
            # HSTS (mod_headers is required) (15768000 seconds = 6 months)
            <IfModule mod_headers.c>
              Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
            </IfModule>
            # Prevent HTTP XSS Trace attack
            RewriteEngine on
            RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
            RewriteRule .* - [F]
          </VirtualHost>
          # SSL Configuration - generated by Mozilla
          SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
          SSLCipherSuite          ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
          SSLHonorCipherOrder     on
          SSLCompression          off
          # OCSP Stapling, only in httpd 2.3.3 and later
          SSLUseStapling          on
          SSLStaplingResponderTimeout 5
          SSLStaplingReturnResponderErrors off
          SSLStaplingCache        shmcb:/var/run/ocsp(128000)
          <Directory /var/www/html/>
            Options +FollowSymlinks
            AllowOverride All
            <IfModule mod_dav.c>
              Dav off
            </IfModule>
            SetEnv HOME /var/www/html
            SetEnv HTTP_HOME /var/www/html
          </Directory>
          Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure

#    - name: Configure SELinux for WebRoot
#      sefcontext:
#        target: '{{ item }}'
#        setype: httpd_sys_rw_content_t
#        state: present
#      with_items:
#       - /var/www/hmtl/nextcloud/data(/.*)?
#       - /var/www/hmtl/nextcloud/config(/.*)?
#       - /var/www/hmtl/nextcloud/apps(/.*)?
#       - /var/www/html/.htaccess
#       - /var/www/html/.user.ini
#    
#    - name: Configure SELinux for MariaDB
#      seboolean:
#        name: httpd_can_network_connect_db
#        state: yes
#        persistent: yes

    - name: Set SELinux to permissive mode
      selinux:
       state: permissive
       policy: targeted
       
    - name: Backup opcache.ini
      command: mv /etc/php.d/opcache.ini /etc/php.d/opcache.ini.bak
      
    - name: Apply recommended opcache config
      blockinfile:
        path: /etc/php.d/opcache.ini
        create: yes
        block: |
          zend_extension=/usr/lib64/php/modules/opcache.so
          opcache.enable=1
          opcache.enable_cli=1
          opcache.interned_strings_buffer=8
          opcache.max_accelerated_files=10000
          opcache.memory_consumption=128
          opcache.save_comments=1
          opcache.revalidate_freq=1
          
#    - name: Configure APCu memcaching
#      lineinfile:
#        path: /var/www/html/config/config.php
#        insertafter: "$CONFIG = array ("
#        line: "'memcache.local' => '\\OC\\Memcache\\APCu',"
        
    - name: Restart httpd to apply config changes
      systemd:
        name: httpd
        state: restarted

    - name: Open firewall
      firewalld:
        port: '{{ item }}'
        state: enabled
        permanent: yes
        immediate: yes
      with_items:
#      - 80/tcp
      - 443/tcp
#- name: Secure Nextcloud instance
#  hosts: all
#  tasks: