---
- name: Install Nextcloud 12 instance
  hosts: all
  become: true
  tasks:
    - name: Import variables
      include_vars:
        file: nextcloud_vars.yml
    
    - include: subtasks/centos_nextcloud.subtask.yml
      when: ansible_distribution == "CentOS"
      
    - include: subtasks/ubuntu_nextcloud.subtask.yml
      when: ansible_distribution == "Ubuntu"