- name: Add keys for '{{ user }}'
  authorized_key:
    user: '{{ user }}'
    state: present
    key: '{{ item }}'
    manage_dir: yes
  with_file:
   - '{{ key_file }}'
   
- name: Add keys for root
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
    manage_dir: yes
  with_file:
   - '{{ key_file }}