#Installs HTTPS NGINX on Ubuntu 16.04
  
- name: Set hostname - Ubuntu
  hostname:
    name: '{{ hostname }}'

- name: Install NGINX and dependencies - Ubuntu
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - nginx
    
- name: Create certificate directory - Ubuntu
  file:
    path: /etc/nginx/ssl/
    state: directory
    
- name: Generate self-signed HTTPS certificates - Ubuntu
  command: openssl req -new -nodes -x509 -subj "/C={{ country }}/ST={{ state }}/L={{ city }}/O={{ org }}/CN={{ hostname }}" -days 3650 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -extensions v3_ca creates=/etc/nginx/ssl/nginx.crt

#- name: Enable required NGINX modules - Ubuntu
#  apache2_module:
#    name: '{{ item }}'
#    state: present
#  with_items: 
#  - ssl
#  - rewrite
#  - headers
  
- name: Create NGINX configuration file - Ubuntu
  blockinfile:
    path: /etc/nginx/sites-available/nginx.conf
    create: yes
    block: |
      server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;

        ssl_protocols TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
        ssl_prefer_server_ciphers on;

        # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
        add_header Strict-Transport-Security max-age=15768000;

        # OCSP Stapling ---
        # fetch OCSP records from URL in ssl_certificate and cache them
        ssl_stapling on;
        ssl_stapling_verify on;

        ## verify chain of trust of OCSP response using Root CA and Intermediate certs
        ssl_trusted_certificate /etc/nginx/ssl/nginx.crt;
      }

- name: Activate NGINX configuration file - Ubuntu
  file:
    src: /etc/nginx/sites-available/nginx.conf
    dest: /etc/nginx/sites-enabled/nginx.conf
    state: link

- name: Restart NGINX and set it to start at boot - Ubuntu
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Open firewall - Ubuntu
  ufw:
    state: enabled
    port: 443
    proto: tcp
    rule: allow