# Installs MySQL and completes mysql_secure_installation on Ubuntu 18.04

- name: Install MySQL and dependencies - Ubuntu
  apt:
    name: mysql-server,python-pip
    state: latest
  
- name: Install MySQL Python module - Ubuntu
  pip:
    name: PyMySQL
    state: latest

- name: Set MySQL to start at boot - Ubuntu
  systemd: 
    name: mysql
    state: started
    enabled: yes

- name: Reload privilege tables - Ubuntu
  command: 'mysql -u root -ne "FLUSH PRIVILEGES"'
  changed_when: False

- name: Remove anonymous users - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  changed_when: False
  with_items:
  - DELETE FROM mysql.user WHERE User=''

- name: Disallow root login remotely - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  changed_when: False
  with_items:
  - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')

- name: Remove test database and access to it - Ubuntu
  command: 'mysql -u root -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True

- name: Reload privilege tables - Ubuntu
  command: 'mysql -u root -ne "FLUSH PRIVILEGES"'
  changed_when: False