#Installs HTTPS Apache and PHP7 Stack on CentOS 7

- name: Set hostname
  hostname:
    name: '{{ hostname }}'
     
- name: Install PHP repo
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    state: present

- name: Install Apache, PHP, and dependencies
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - httpd
    - php70w
    - php70w-dom
    - php70w-mbstring
    - php70w-gd
    - php70w-pdo
    - php70w-json
    - php70w-xml
    - php70w-zip
    - php70w-curl
    - php70w-mcrypt
    - php70w-pear
    - php70w-mysql
    - setroubleshoot-server
    - unzip
    - libselinux-python
    - mod_ssl

- name: Restart Apache and set to start at boot
  systemd: 
    name: httpd
    state: restarted
    enabled: yes

- name: Create cert directory
  file:
    path: /etc/httpd/ssl/
    state: directory
    
- name: Generate HTTPS Certs
  command: openssl req -new -nodes -x509 -subj "/C={{ country }}/ST={{ state }}/L={{ city }}/O={{ org }}/CN={{ hostname }}" -days 3650 -keyout /etc/httpd/ssl/lamp.key -out /etc/httpd/ssl/lamp.crt -extensions v3_ca creates=/etc/httpd/ssl/lamp.crt

- name: Create Apache config file
  blockinfile:
    path: /etc/httpd/conf.d/lamp.conf
    create: yes
    block: |
      <VirtualHost *:443>
        ServerName {{ hostname }}
        ServerAlias {{ ansible_default_ipv4.address }}
        SSLEngine on
        SSLCertificateFile      /etc/httpd/ssl/lamp.crt
        SSLCertificateKeyFile /etc/httpd/ssl/lamp.key
        # HSTS (mod_headers is required) (15768000 seconds = 6 months)
        <IfModule mod_headers.c>
          Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
        </IfModule>
        # Prevent HTTP XSS Trace attack
        RewriteEngine on
        RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
        RewriteRule .* - [F]
      </VirtualHost>
      # SSL Configuration - generated by Mozilla
      SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
      SSLCipherSuite          ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      SSLHonorCipherOrder     on
      SSLCompression          off
      # OCSP Stapling, only in httpd 2.3.3 and later
      SSLUseStapling          on
      SSLStaplingResponderTimeout 5
      SSLStaplingReturnResponderErrors off
      SSLStaplingCache        shmcb:/var/run/ocsp(128000)
      <Directory /var/www/html/>
        Options +FollowSymlinks
        AllowOverride All
        <IfModule mod_dav.c>
          Dav off
        </IfModule>
        SetEnv HOME /var/www/html
        SetEnv HTTP_HOME /var/www/html
      </Directory>
      Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure

- name: Restart httpd to apply config changes
  systemd:
    name: httpd
    state: restarted

- name: Open firewall
  firewalld:
    port: 443/tcp
    state: enabled
    permanent: yes
    immediate: yes