#Installs PHP7 on CentOS 7
- name: Install IUS Community repository - CentOS
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Install PHP and dependencies - CentOS
  yum:
    name: mod_php72u,php72u,php72u-cli,php72u-common,php72u-devel,php72u-fpm,php72u-imap,php72u-intl,php72u-process,php72u-dom,php72u-mbstring,php72u-gd,php72u-pdo,php72u-json,php72u-xml,php72u-zip,php72u-curl,php72u-mysqlnd
    state: latest