#Installs PHP7 on CentOS 7
- name: Install IUS Community repository - CentOS
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Install PHP and dependencies - CentOS
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - mod_php70u
    - php70u
    - php70u-cli
    - php70u-common
    - php70u-devel
    - php70u-fpm
    - php70u-imap
    - php70u-intl
    - php70u-pecl-apcu
    - php70u-pecl-smbclient
    - php70u-process
    - php70u-dom
    - php70u-mbstring
    - php70u-gd
    - php70u-pdo
    - php70u-json
    - php70u-xml
    - php70u-zip
    - php70u-curl
    - php70u-mcrypt
    - php70u-pear
    - php70u-mysqlnd