---
- name: Install MariaDB and complete mysql_secure_installation
  hosts: all
  become: true
  tasks:
    - name: Import variables
      include_vars:
        file: mysql_vars.yml
    
    - name: Install MariaDB and dependencies
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
      - mariadb-server
      - mariadb-devel
      - python-pip
      - gcc
      - python-devel
          
    - name: Install MySQLDb Python Module
      pip:
        name: MySQL-Python
        state: latest
        
    - name: Set MariaDB to start at boot
      systemd: 
        name: mariadb
        state: started
        enabled: yes

    - name: Set root password
      mysql_user: 
        name: root
        host: '{{ item }}'
        password: '{{ mysql_root_password }}'
        state: present
        check_implicit_admin: yes
        login_password: '{{ mysql_root_password }}'
      with_items:
        - localhost
        - 127.0.0.1
        - ::1

    - name: Add .my.cnf
      template: 
        src: '{{ mysql_root_mycnf }}'
        dest: /root/.my.cnf 
        owner: root
        group: root
        mode: 0600
     
    - name: Reload privilege tables
      command: 'mysql -ne "FLUSH PRIVILEGES"'
      changed_when: False

    - name: Remove anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    - name: Disallow root login remotely
      command: 'mysql -ne "{{ item }}"'
      changed_when: False
      with_items:
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    
    - name: Remove test database and access to it
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DROP DATABASE test
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
      changed_when: False
      ignore_errors: True

    - name: Reload privilege tables
      command: 'mysql -ne "FLUSH PRIVILEGES"'
      changed_when: False