---
- name: Install MariaDB or MySQL and complete mysql_secure_installation
  hosts: all
  become: true
  tasks:
    - name: Import variables
      include_vars:
        file: mysql_vars.yml
    
    - include: subtasks/centos_mysql.subtask.yml
      when: ansible_distribution == "CentOS"
      
    - include: subtasks/ubuntu_mysql.subtask.yml
      when: ansible_distribution == "Ubuntu"