- name: Install EPEL repo
  package:
    name: epel-release
    state: latest

- name: Install oVirt Guest Agent
  package:
    name: ovirt-guest-agent
    state: latest

- name: Activate oVirt Guest Agent
  systemd:
    name: ovirt-guest-agent
    state: started
    enabled: yes