#Prepare Ubuntu to work with Ansible
- name: Confirm installation of Ansible dependencies on Ubuntu
  raw: "sudo apt-get update -y && sudo apt-get install -y python aptitude"
  when: ansible_distribution == "Ubuntu"
  
#Update Host
- import_tasks: centos_update.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_update.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Install Base Packages        
- name: Install base packages
  package:
    name: nano,ntp,wget,epel-release
    state: latest

- name: Install oVirt Guest Agent
  package:
    name: ovirt-guest-agent
    state: latest

# Configure oVirt Guest Agent
- import_tasks: centos_ovirtguestagent.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_ovirtguestagent.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Activate firewall   
- import_tasks: centos_firewall.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_firewall.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Install SSH Keys
- import_tasks: ssh_auth_config.subtask.yml 

#Configure NTP
- import_tasks: centos_ntp.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_ntp.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Remove Security Vulnerabilities
- import_tasks: centos_hardening.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_hardening.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Reboot Host
- import_tasks: reboot.subtask.yml