#Update Host
- import_tasks: centos_update.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_update.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Install Base Packages        
- name: Install base packages
  package:
    name: nano,wget,open-vm-tools
    state: latest

#Activate firewall   
- import_tasks: centos_firewall.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_firewall.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Install SSH Keys
- import_tasks: ssh_auth_config.subtask.yml 

#Mitigate Security Vulnerabilities
- import_tasks: centos_hardening.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_hardening.subtask.yml
  when: ansible_distribution == "Ubuntu"
