# Set the SFTP server location based on OS type (for hardened SSH config)
- name: "Set SFTP server location - CentOS"
  set_fact:
    sshd_sftp_server: /usr/libexec/openssh/sftp-server
  when: ansible_distribution == "CentOS"

- name: "Set SFTP server location - Ubuntu"
  set_fact:
    sshd_sftp_server: /usr/lib/openssh/sftp-server
  when: ansible_distribution == "Ubuntu"

#Update Host
- import_tasks: centos_update.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_update.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Install Base Packages        
- name: Install base packages
  package:
    name: nano,wget,open-vm-tools
    state: latest

#Activate firewall   
- import_tasks: centos_firewall.subtask.yml
  when: ansible_distribution == "CentOS"
- import_tasks: ubuntu_firewall.subtask.yml
  when: ansible_distribution == "Ubuntu"

#Install SSH Keys
- import_tasks: ssh_auth_config.subtask.yml 

#Mitigate Security Vulnerabilities
- import_tasks: hardening.subtask.yml

