#Configures rsyslogd on Ubuntu 16.04
  
- name: Configure rsyslogd - Ubuntu
  blockinfile:
    path: /etc/rsyslog.d/50-default.conf
    block: |
      *.* @{{syslog_server}}:{{syslog_port}};RSYSLOG_SyslogProtocol23Format

- name: Restart rsyslog and set it to start at boot - Ubuntu
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes