- name: Set allowed cipher suites - Ubuntu
  lineinfile:
    name: /etc/ssh/sshd_config
    insertafter: "ServerKeyBits 1024\n"
    line: "{{item}}"
  with_items:
   - KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
   - Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
   - MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
   
- name: Disable root logins by password - Ubuntu
  lineinfile:
    name: /etc/ssh/sshd_config
    line: "PermitRootLogin yes"
    state: absent

- name: Enable root logins by public key - Ubuntu
  blockinfile:
    name: /etc/ssh/sshd_config
    insertafter: "LoginGraceTime 120"
    block: |
      PermitRootLogin without-password

- name: Restart sshd - Ubuntu
  systemd:
    state: restarted
    name: sshd
    enabled: yes

- name: Disable TCP timestamps - Ubuntu
  lineinfile:
    name: /etc/sysctl.conf
    insertafter:
    line: net.ipv4.tcp_timestamps = 0

- name: Refresh sysctl.conf - Ubuntu
  command: sysctl -p