---
- name: Update host
  hosts: all
  become: true
  tasks:

    - include: subtasks/centos_update.subtask.yml
      when: ansible_distribution == "CentOS"
      
    - include: subtasks/ubuntu_update.subtask.yml
      when: ansible_distribution == "Ubuntu"    